/***************************************************************
* Copyright (C) 2011 Jeremy Reagan, All Rights Reserved.
* I may be reached via email at: jeremy.reagan@live.com
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; under version 2
* of the License.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
****************************************************************/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL7Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HL7Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church 
        ///High 
        ///Chestnut 
        ///Elm 
        ///B 
        ///2nd 
        ///Walnut 
        ///Main North
        ///Maple 
        ///Maple 
        ///Center 
        ///Main South
        ///Washington 
        ///Pine 
        ///River 
        ///South 
        ///Union 
        ///Water 
        ///Main West
        ///Main East
        ///Park 
        ///School 
        ///Spring 
        ///Oak 
        ///Prospect 
        ///Market 
        ///North 
        ///3rd 
        ///Front 
        ///Park 
        ///Washington 
        ///Highland 
        ///Cedar 
        ///Central 
        ///Spruce 
        ///State 
        ///West 
        ///Franklin 
        ///Ridge 
        ///4th 
        ///Church 
        ///Lincoln 
        ///Pleasant 
        ///Bridge 
        ///Cherry 
        ///East 
        ///Locust 
        ///Winding  
        ///Route 1
        ///1st 
        ///5th 
        ///Cherry  
        ///Mill 
        ///Park Place
        ///Route 30
        ///2nd 
        ///Academy 
        ///Adams 
        ///Beech 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Address_Names {
            get {
                return ResourceManager.GetString("Address_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacob
        ///Ethan
        ///Michael
        ///Alexander
        ///William
        ///Joshua
        ///Daniel
        ///Jayden
        ///Noah
        ///Anthony
        ///Christopher
        ///Aiden
        ///Matthew
        ///David
        ///Andrew
        ///Joseph
        ///Logan
        ///James
        ///Ryan
        ///Benjamin
        ///Elijah
        ///Gabriel
        ///Christian
        ///Nathan
        ///Jackson
        ///John
        ///Samuel
        ///Tyler
        ///Dylan
        ///Jonathan
        ///Caleb
        ///Nicholas
        ///Gavin
        ///Mason
        ///Evan
        ///Landon
        ///Angel
        ///Brandon
        ///Lucas
        ///Isaac
        ///Isaiah
        ///Jack
        ///Jose
        ///Kevin
        ///Jordan
        ///Justin
        ///Brayden
        ///Luke
        ///Liam
        ///Carter
        ///Owen
        ///Connor
        ///Zachary
        ///Aaron
        ///Robert
        ///Hunter
        ///Thomas
        ///Adrian
        ///Cameron
        ///Wyatt
        ///Chase
        ///Julian
        ///Austin
        ///Charles
        ///Jeremiah [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Boy_Names {
            get {
                return ResourceManager.GetString("Boy_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isabella
        ///Emma
        ///Olivia
        ///Sophia
        ///Ava
        ///Emily
        ///Madison
        ///Abigail
        ///Chloe
        ///Mia
        ///Elizabeth
        ///Addison
        ///Alexis
        ///Ella
        ///Samantha
        ///Natalie
        ///Grace
        ///Lily
        ///Alyssa
        ///Ashley
        ///Sarah
        ///Taylor
        ///Hannah
        ///Brianna
        ///Hailey
        ///Kaylee
        ///Lillian
        ///Leah
        ///Anna
        ///Allison
        ///Victoria
        ///Avery
        ///Gabriella
        ///Nevaeh
        ///Kayla
        ///Sofia
        ///Brooklyn
        ///Riley
        ///Evelyn
        ///Savannah
        ///Aubrey
        ///Alexa
        ///Peyton
        ///Makayla
        ///Layla
        ///Lauren
        ///Zoe
        ///Sydney
        ///Audrey
        ///Julia
        ///Jasmine
        ///Arianna
        ///Claire
        ///Brooke
        ///Amelia
        ///Morgan
        ///Destiny
        ///Bella
        ///Madelyn
        ///Katherine
        ///Kylie
        ///Maya
        ///Aaliyah
        ///Madeline
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Girl_Names {
            get {
                return ResourceManager.GetString("Girl_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///JONES
        ///BROWN
        ///DAVIS
        ///MILLER
        ///WILSON
        ///MOORE
        ///TAYLOR
        ///ANDERSON
        ///THOMAS
        ///JACKSON
        ///WHITE
        ///HARRIS
        ///MARTIN
        ///THOMPSON
        ///GARCIA
        ///MARTINEZ
        ///ROBINSON
        ///CLARK
        ///RODRIGUEZ
        ///LEWIS
        ///LEE
        ///WALKER
        ///HALL
        ///ALLEN
        ///YOUNG
        ///HERNANDEZ
        ///KING
        ///WRIGHT
        ///LOPEZ
        ///HILL
        ///SCOTT
        ///GREEN
        ///ADAMS
        ///BAKER
        ///GONZALEZ
        ///NELSON
        ///CARTER
        ///MITCHELL
        ///PEREZ
        ///ROBERTS
        ///TURNER
        ///PHILLIPS
        ///CAMPBELL
        ///PARKER
        ///EVANS
        ///EDWARDS
        ///COLLINS
        ///STEWART
        ///SANCHEZ
        ///MORRIS
        ///ROGERS
        ///REED
        ///COOK
        ///MORGAN
        ///BELL
        ///MURPHY
        ///BAILEY
        ///RIVERA
        ///COOPER
        ///RICHARDSON
        ///COX
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Last_Names {
            get {
                return ResourceManager.GetString("Last_Names", resourceCulture);
            }
        }
    }
}
